name: Build and Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Deploy to Production Environment
      - name: Deploy to Firebase (Production)
        if: github.ref == 'refs/heads/master'
        run: npm i && npm run build && npm run export
        run: firebase deploy --only hosting:prod --token AIzaSyAW_g8c4M9c3GMFL3Ui-bVnukWhZdHHCDU
        env:
          FIREBASE_TOKEN: AIzaSyAW_g8c4M9c3GMFL3Ui-bVnukWhZdHHCDU

      # Deploy to Development Environment
      - name: Deploy to Firebase (Development)
        if: github.ref == 'refs/heads/dev'
        run: firebase deploy --only hosting:dev --token AIzaSyAW_g8c4M9c3GMFL3Ui-bVnukWhZdHHCDU
        env:
          FIREBASE_TOKEN: AIzaSyAW_g8c4M9c3GMFL3Ui-bVnukWhZdHHCDU
